#!/bin/bash
#
# Init file for Apache Kafka
#
# chkconfig: 35 85 15
# description: Apache Kafka is a distributed publish-subscribe messaging system
# processname: kafka
# config: /etc/kafka/servers.properties
# pidfile: /var/run/kafa.pid

. /etc/rc.d/init.d/functions

SYSCONFIG="/etc/sysconfig/kafka"
KAFKA_BASEDIR=${KAFKA_BASEDIR-/usr/lib/kafka/default}
PIDFILE="/var/run/kafka.pid"
KAFKA_USER="kafka"
OUTFILE="/var/log/kafka/kafka-server.out"

. "$SYSCONFIG" || true

CMD="$KAFKA_BASEDIR/bin/kafka-run-class.sh kafka.Kafka /etc/kafka/server.properties >> $OUTFILE & echo \$! > $PIDFILE"

start()
{
  echo -n $"Starting kafka: "
  touch $PIDFILE && chown kafka $PIDFILE
  export KAFKA_OPTS
  daemon --user $KAFKA_USER --pidfile $PIDFILE "$CMD"
  RETVAL=$?
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/kafka && success || failure
  echo
  return $RETVAL
}

stop()
{
  echo -n $"Stopping kafka: "
  if [ -f "$PIDFILE" ] ; then
    KAFKA_PID=$(head -1 $PIDFILE | perl -pi -e "s/^(\d+).*/\1/"| grep -e "^[0-9]\+")
    if [ -n "$KAFKA_PID" ] ; then
      pkill -P $(head -1 $PIDFILE | cut -f 1 -d ' ') -f "kafka.Kafka"
      #killproc -p $PIDFILE kafka
      RETVAL=$?
    else
      echo "PIDFILE: $PIDFILE is not valid."
      RETVAL=1
    fi
  else
    echo "PIDFILE: $PIDFILE not exists"
    RETVAL=1
  fi
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/kafka
  return $RETVAL
}

restart () {
  stop
  start
}

RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f /var/lock/subsys/kafka ] && restart || :
    ;;
  status)
    status -p $PIDFILE kafka
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL
